apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: castai-agent
  namespace: castai-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: castai-agent
      sourceRef:
        kind: HelmRepository
        name: castai-helm
        namespace: flux-system
  values:
    apiKey: "0d84debfa3f0be50c3454ab645f8b04d1db0e096a4a0fd674675e04794508635"      # Replace this
    provider: gke
    createNamespace: true
    readonly: false                        # This enables read-only mode


