apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: castai-agent
  namespace: castai-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: castai-agent
      sourceRef:
        kind: HelmRepository
        name: castai-helm
        namespace: flux-system
  values:
    apiKey: ""      # Replace this
    provider: gke
    createNamespace: true
    readonly: false                        # This enables read-only mode
    replicaCount: 1

