apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: castai
  namespace: flux-system
spec:
  interval: 1m
  path: ./castai  # Relative to your GitRepository root
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd
    namespace: flux-system
  wait: true
  timeout: 2m

