apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - castai-helm-repo.yaml
  - castai-agent-readonly.yaml
  - cluster-controller.yaml
  - workload-autoscaler.yaml
  - spot-handler.yaml
  - evictor.yaml
  - kvisor.yaml   # optional

