apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: castai-kvisor
  namespace: castai-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: castai-kvisor
      sourceRef:
        kind: HelmRepository
        name: castai-helm
        namespace: flux-system
  values:
    castai:
      apiKey: "0d84debfa3f0be50c3454ab645f8b04d1db0e096a4a0fd674675e04794508635"
      clusterID: "d781172d-68b7-4fb8-a65d-98061fbdff64"
    controller:
      extraArgs:
        kube-linter-enabled: true
        image-scan-enabled: true
        kube-bench-enabled: true
        kube-bench-cloud-provider: gke

