apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: castai-spot-handler
  namespace: castai-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: castai-spot-handler
      sourceRef:
        kind: HelmRepository
        name: castai-helm
        namespace: flux-system
  values:
    castai:
      provider: gke
      clusterID: "d781172d-68b7-4fb8-a65d-98061fbdff64"
